-- +goose Up
-- +goose StatementBegin
-- THIS FILE WAS GENERATED BY GORMITE, EDIT IT IF YOU WANT <3

CREATE SCHEMA public;
CREATE SEQUENCE user__id__seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE user_profile__id__seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE "user" (id INT NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(10) NOT NULL, identity_type VARCHAR(255) NOT NULL, code VARCHAR(255), full_name VARCHAR(255) DEFAULT 'Anonymous' NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY(id));
CREATE INDEX index_full_name ON "user" (full_name) WHERE (is_active = true);
CREATE UNIQUE INDEX idx__user__email__uniq ON "user" (email) WHERE (identity_type = 'email');
CREATE UNIQUE INDEX idx__user__phone__uniq ON "user" (phone) WHERE (identity_type = 'phone');
CREATE TABLE user_profile (id INT NOT NULL, user_id INT NOT NULL, age INT NOT NULL, PRIMARY KEY(id));
ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB405A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- THIS FILE WAS GENERATED BY GORMITE, EDIT IT IF YOU WANT <3

DROP SEQUENCE user__id__seq CASCADE;
DROP SEQUENCE user_profile__id__seq CASCADE;
ALTER TABLE user_profile DROP CONSTRAINT FK_D95AB405A76ED395;
DROP TABLE "user";
DROP TABLE user_profile;
-- +goose StatementEnd
